# Python Control Structures

## Topics

-   More on Statements and Syntax
-   Control Structures and Loops
-   Conditional Logic
-   Iterators
-   Comprehensions

## Suggested Readings

-   [Lutz, 2019, Part III, Chapter 10. Introducing Python Statements](https://learning.oreilly.com/library/view/learning-python-6th/9781098171292/ch10.html)
-   [Lutz, 2019, Part III, Chapter 11. Assignments, Expressions, and Prints](https://learning.oreilly.com/library/view/learning-python-6th/9781098171292/ch11.html)
-   [Lutz, 2019, Part III, Chapter 12. if and match Selection](https://learning.oreilly.com/library/view/learning-python-6th/9781098171292/ch12.html)
-   [Lutz, 2019, Part III, Chapter 13. while and for Loops](https://learning.oreilly.com/library/view/learning-python-6th/9781098171292/ch13.html)
-   [Lutz, 2019, Part III, Chapter 14. Iterations and Comprehensions](https://learning.oreilly.com/library/view/learning-python-6th/9781098171292/ch14.html)
-   [Lutz, 2019, Part III, Chapter 15: The Documentations Interlude](https://learning.oreilly.com/library/view/learning-python-6th/9781098171292/ch15.html)
-   [Variables, Expressions, Statements, Types (Python Notes)](https://thomas-cokelaer.info/tutorials/python/variables.html)
-   [More Control Flow Tools (Python Docs)](https://docs.python.org/3/tutorial/controlflow.html)
-   [If ... Then (W3S)](https://www.w3schools.com/python/python_conditions.asp)
-   [Iterators (GFG)](https://www.geeksforgeeks.org/iterators-in-python/)

## Videos

### Control Structures

<iframe id="kmsembed-1_0oc8qocg" width="400" height="285" src="https://kaltura-prod.its.virginia.edu/embed/secure/iframe/entryId/1_0oc8qocg/uiConfId/50243942/pbc/353035032/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="DS 5100 M03 Control Structures"></iframe><br />

### Iterables and Iterators

<iframe id="kmsembed-1_2nuu4az4" width="400" height="285" src="https://kaltura-prod.its.virginia.edu/embed/secure/iframe/entryId/1_2nuu4az4/uiConfId/50243942/pbc/353035032/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="DS 5100 M03 Iterables and Iterators"></iframe><br />

### Comprehensions

<iframe id="kmsembed-1_lmz0pbeg" width="400" height="285" src="https://kaltura-prod.its.virginia.edu/embed/secure/iframe/entryId/1_lmz0pbeg/uiConfId/50243942/pbc/353035032/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="DS 5100 M03 Comprehensions"></iframe><br />

### Nested Comprehensions

<iframe id="kmsembed-1_kmjd2a3x" width="400" height="285" src="https://kaltura-prod.its.virginia.edu/embed/secure/iframe/entryId/1_kmjd2a3x/uiConfId/50243942/pbc/353035032/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="DS 5100 M03 Nested Comprehensions"></iframe><br />