project:
  title: "PFDS Bootcamp"
  type: book
  output-dir: docs

execute:
  freeze: true
  
book:
  title: "Programming for Data Science Bootcamp"
  author: "Rafael C. Alvarado"
  date: "03/06/2025"
  reader-mode: false
  page-navigation: true
  repo-actions: [edit]
  repo-url: "https://github.com/ontoligent/programming-for-data-science"
  chapters:
    - index.qmd # 00 Welcome         
    - part: modules/m02/m02-intro.qmd # Python Introduction
      chapters:
        - notebooks/M02_BasicPython/on-data.qmd
        - notebooks/M02_BasicPython/python-object-types.qmd
        - notebooks/M02_BasicPython/M02-01-DataTypes.ipynb
        - notebooks/M02_BasicPython/M02-02-Numbers.ipynb
        - notebooks/M02_BasicPython/M02-03-Booleans.ipynb
        - notebooks/M02_BasicPython/M02-04-Strings.ipynb
        - notebooks/M02_BasicPython/M02-05-Structures.ipynb
        - notebooks/M02_BasicPython/M02-06-AsideOnImmutables.ipynb
        - exercises/M02-Exercises.qmd
        
    - part: modules/m03/m03-intro.qmd # Python Control Structures
      chapters:
        - notebooks/M03_ControlStructures/vals-vars-expressions-statements.qmd
        - notebooks/M03_ControlStructures/M03-01-ControlStructures.ipynb
        - notebooks/M03_ControlStructures/M03-02-IterablesAndIterators.ipynb
        - notebooks/M03_ControlStructures/M03-03-Comprehensions.ipynb
        - notebooks/M03_ControlStructures/M03-04-NestedComprehensions.ipynb
        - exercises/M03-Exercises.qmd
        
    - part: modules/m04/m04-intro.qmd # Python Functions
      chapters: 
        - notebooks/M04_PythonFunctions/M04-01-Functions.ipynb
        - notebooks/M04_PythonFunctions/M04-02-Importing.ipynb
        - notebooks/M04_PythonFunctions/M04-03-LambdaFunctions.ipynb
        - notebooks/M04_PythonFunctions/M04-04-RecursiveFunctions.ipynb
        - notebooks/M04_PythonFunctions/M04-05-Scope.ipynb
        - notebooks/M04_PythonFunctions/M04-06-FunctionsCallingFunctions.ipynb
        - exercises/M04-Exercises.qmd
        
    - part: modules/m05/m05-intro.qmd # Python NumPy
      chapters:
        - notebooks/M05_NumPy/M05-00-Time.ipynb
        - notebooks/M05_NumPy/M05-01-BasicFileIO.ipynb
        - notebooks/M05_NumPy/M05-02-NumpyDesign.ipynb
        - notebooks/M05_NumPy/M05-03-NumPyIndexing.ipynb
        - notebooks/M05_NumPy/M05-04-NumPyOperating.ipynb
        - notebooks/M05_NumPy/M05-05-NumPyFunctions.ipynb
        - exercises/M05-Exercises.qmd
        
    - part: modules/m06/m06-intro.qmd # Python Pandas
      chapters:
        - notebooks/M06_Pandas/M06-00-IntroducingPandas.ipynb
        - notebooks/M06_Pandas/M06-01-ExploringPandas.ipynb
        - notebooks/M06_Pandas/M06-02-DeeperIntoPandas.ipynb
        - notebooks/M06_Pandas/M06-03-NarrowWide.ipynb
        - notebooks/M06_Pandas/M06-04-MethodChaining.ipynb
        - notebooks/M06_Pandas/M06-05-Pandas-and-SQL.ipynb
        - exercises/M06-Exercises.qmd
        
    - part: modules/m10/m10-intro.qmd # R Introduction
      chapters: 
        - notebooks/M10_RBasics/M10-01-Intro.ipynb
        - notebooks/M10_RBasics/M10-02-DataTypes.ipynb
        - notebooks/M10_RBasics/M10-03-DataStructures.ipynb
        - notebooks/M10_RBasics/M10-04-DataFrames.ipynb
        - notebooks/M10_RBasics/M10-05-ControlStructures.ipynb
        - notebooks/M10_RBasics/M10-06-Functions.ipynb
        - exercises/M10-Exercises.qmd
        
    - part: modules/m11/m11-intro.qmd # R Dplyr
      chapters: 
        - notebooks/M11_RDplyr/M11-01-Tibbles.ipynb
        - notebooks/M11_RDplyr/M11-02-Dplyr.ipynb
        - exercises/M11-Exercises.qmd

    - part: modules/m12/m12-intro.qmd # R Visualization
      chapters:
        - notebooks/M12_RViz/M12-00-AGrammarOfGraphics.ipynb      
        - notebooks/M12_RViz/M12-01-GettingStartedWithGGPlot.ipynb
        - notebooks/M12_RViz/M12-02-RMarkdown.ipynb
        - notebooks/M12_RViz/M12-03-Qplot-and-Plotly.ipynb
        - notebooks/M12_RViz/M12-04-Plotnine.ipynb
        - exercises/M12-Exercises.qmd
          
  sidebar:
    style: docked
    reader-mode: false
    # style: floating
    background: light
    collapse-level: 1
    subtitle: Summer 2024


format:
  html:
    toc: true
    theme: cosmo
    number-sections: false
    fig-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true
    reader-mode: false

bibliography:
  - refs.bib
