# R Introduction

## Topics

-   Present R basics — syntax, data types, and operators
-   Present R data structures – vectors, lists, matrices, and data frames
-   Create a function in R, and use it in a program

## Readings

### Required

-   [W3Schools R Tutorial](https://www.w3schools.com/r/default.asp)
-   [W3Schools R Data Structures](https://www.w3schools.com/r/r_vectors.asp)

### Optional

-   [Yau, R Tutorial, "R Introduction"](http://www.r-tutor.com/r-introduction)
    -   Super concise.

## Videos

<iframe src="https://kaltura-prod.its.virginia.edu/embedplaylist/secure/embed/v2/0/playlistId/1_p5eo6ahu/uiConfId/55951532" width="960px" height="540px" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerpolicy="no-referrer-when-downgrade" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>