# Python Pandas

## Topics

-   Introduce Pandas and its relationship to NumPy
-   Understand difference between Series and DataFrames
-   Understand role of indexes in Pandas
-   Review fundamental methods in Pandas

## Suggested Readings

-   [McKinney 2023, Chapter 5: Getting Started with Pandas](https://wesmckinney.com/book/pandas-basics)
-   [Getting Started in Pandas (Official)](https://pandas.pydata.org/docs/getting_started/index.html#getting-started)

## Videos

### Introducing Pandas

<iframe id="kmsembed-1_9aoaw9hx" width="400" height="285" src="https://kaltura-prod.its.virginia.edu/embed/secure/iframe/entryId/1_9aoaw9hx/uiConfId/50243942/pbc/353035032/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="DS 5100 M06 Introducing Pandas"></iframe><br />

### Exploring Pandas

<iframe id="kmsembed-1_tn181naz" width="400" height="285" src="https://kaltura-prod.its.virginia.edu/embed/secure/iframe/entryId/1_tn181naz/uiConfId/50243942/pbc/353035032/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="DS 5100 M06 Exploring Pandas"></iframe><br />

### Diving Deeper Into Pandas

<iframe id="kmsembed-1_kr019fk4" width="400" height="285" src="https://kaltura-prod.its.virginia.edu/embed/secure/iframe/entryId/1_kr019fk4/uiConfId/50243942/pbc/353035032/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="DS 5100 M06 Diving Deeper Into Pandas"></iframe><br />
