# R Dplyr

## Topics

-   The Tidyverse
-   Tibbles, a lightweight version of data frames
-   Data transformations using dplyr verbs

## Readings

### Required

-   [RFDS Explore 5 Data Transformation](https://r4ds.had.co.nz/transform.html)
    -   (`dplyr`)
-   [RDFS Wrangle 10 Tibbles](https://r4ds.had.co.nz/tibbles.html)
-   [RDFS Wrangle 11 Data Import](https://r4ds.had.co.nz/data-import.html)
-   [RDFS Wrangle 12 Tidy data](https://r4ds.had.co.nz/tidy-data.html)

### Optional

-   [Peng, 2022, "Managing Data Frames with the dplyr package"](https://bookdown.org/rdpeng/rprogdatascience/managing-data-frames-with-the-dplyr-package.html)

## Videos

<iframe src="https://kaltura-prod.its.virginia.edu/embedplaylist/secure/embed/v2/0/playlistId/1_26krjges/uiConfId/55951532" width="960px" height="540px" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerpolicy="no-referrer-when-downgrade" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>