# Python Pandas

## Topics

-   Introduce Pandas and its relationship to NumPy
-   Understand difference between Series and DataFrames
-   Understand role of indexes in Pandas
-   Review fundamental methods in Pandas

## Readings

### Required

-   [McKinney 2023, Chapter 5: Getting Started with Pandas](https://wesmckinney.com/book/pandas-basics)
-   [Getting Started in Pandas (Official)](https://pandas.pydata.org/docs/getting_started/index.html#getting-started)

## Videos

<iframe src="https://kaltura-prod.its.virginia.edu/embedplaylist/secure/embed/v2/0/playlistId/1_pz1ktgmw/uiConfId/55951532" width="960px" height="540px" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerpolicy="no-referrer-when-downgrade" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>